# Sandbox Jupyter Notebook for Source2Suffering

Modules needed that can be load with Jupyter Lab

- xarray
- cartopy
- openpyxl

Modules needed that can't be load with Jupyter Lab

- mapclassify 2.4.3
   - Provide in geopandas/0.12.2-foss-2022a
         - Works if we load geopandas from Jupyter Lab

---

Change path to current directory path

In [11]:
import os

notebook_path = os.getcwd()  # Current path
print("Directory of the notebook:", notebook_path)
notebook_path = notebook_path

scripts_dir = "/data/brussel/vo/000/bvo00012/vsc11137/source2suffering"
data_dir = scripts_dir+"/data/"

Directory of the notebook: /vscmnt/brussel_pixiu_data/_data_brussel/vo/000/bvo00012/vsc11137/source2suffering/sandbox


Libraries

In [12]:
#%%  ----------------------------------------------------------------
# import and path
# ----------------------------------------------------------------

import xarray as xr
import pickle as pk
import time
# from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib as mpl
import mapclassify as mc
from copy import deepcopy as cp
import os
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import cartopy.crs as ccrs
import cartopy as cr
import geopandas as gpd
import sys
from operator import index
import numpy as np
import pandas as pd
from scipy import interpolate
from scipy import stats as sts
import regionmask as rm
import glob

sys.path.append(os.path.abspath(scripts_dir))

## Visualization of objects

exposure_peryear_perage_percountry_{extr}_{ISIMIP_run}.pkl

In [13]:
with open(data_dir+'{}/{}/exposure_peryear_perage_percountry_{}_{}.pkl'.format('pickles_v3','heatwavedarea','heatwavedarea',5), 'rb') as f:
            da_exposure_peryear_perage_percountry_strj_heatwavedarea_sim=pk.load(f)   

In [14]:
print(type(da_exposure_peryear_perage_percountry_strj_heatwavedarea_sim))
print(np.shape(da_exposure_peryear_perage_percountry_strj_heatwavedarea_sim))
print(da_exposure_peryear_perage_percountry_strj_heatwavedarea_sim)

<class 'xarray.core.dataarray.DataArray'>
(177, 154, 101, 21)
<xarray.DataArray (country: 177, time: 154, ages: 101, GMT: 21)>
array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          

In [15]:
da_subset = da_exposure_peryear_perage_percountry_strj_heatwavedarea_sim.sel(country='Egypt')
non_nan_indices = np.where(~np.isnan(da_subset.values))
print(non_nan_indices)

(array([  0,   0,   0, ..., 153, 153, 153]), array([  0,   0,   0, ..., 100, 100, 100]), array([ 0,  1,  2, ..., 18, 19, 20]))


In [16]:
print(da_subset.sel(time=2030,ages=10,GMT=1))

<xarray.DataArray ()>
array(0.090036)
Coordinates:
    country  <U32 'Egypt'
    time     int64 2030
    ages     int64 10
    GMT      int64 1


In [17]:
da_values_all_times = da_subset.sel(time=slice(None))  # slice(None) sélectionne toutes les valeurs de la dimension time
y_values = da_values_all_times.sel(ages=10, GMT=20)

plt.plot(da_subset.sel(ages=10,GMT=20),y_values)
plt.show()
plt.savefig(scripts_dir+'/sandbox/figures/fig1.png')

calc_lifetime_exposure()

In [18]:
with open(data_dir+'{}/{}/lifetime_exposure_percountry_perrun_GMT.pkl'.format('pickles_v3','heatwavedarea'), 'rb') as f:
            ds_le=pk.load(f)   

In [19]:
ds_le

<xarray.Dataset>
Dimensions:            (run: 12, GMT: 21, country: 177, birth_year: 61)
Coordinates:
  * country            (country) object 'Afghanistan' 'Angola' ... 'Zimbabwe'
  * birth_year         (birth_year) int64 1960 1961 1962 1963 ... 2018 2019 2020
  * run                (run) int64 1 2 3 4 5 6 7 8 9 10 11 12
  * GMT                (GMT) int64 0 1 2 3 4 5 6 7 8 ... 13 14 15 16 17 18 19 20
Data variables:
    lifetime_exposure  (run, GMT, country, birth_year) float64 nan nan ... 53.4

exposure_trends{extr}

In [20]:
with open(data_dir+'{}/{}/lifetime_exposure_trends_regions.pkl'.format('pickles_v3','heatwavedarea'), 'rb') as f:
            ds_le_trends_regions=pk.load(f)   

In [21]:
ds_le_trends_regions

<xarray.Dataset>
Dimensions:                      (run: 12, GMT: 21, region: 46, year: 61,
                                  country: 177, basin: 220)
Coordinates:
  * region                       (region) int64 0 1 2 3 4 5 ... 41 42 43 44 45
  * country                      (country) int64 0 1 2 3 4 ... 173 174 175 176
  * basin                        (basin) int64 0 1 2 3 4 ... 221 222 223 224 225
  * run                          (run) int64 1 2 3 4 5 6 7 8 9 10 11 12
  * GMT                          (GMT) int64 0 1 2 3 4 5 6 ... 15 16 17 18 19 20
  * year                         (year) int64 1960 1961 1962 ... 2018 2019 2020
Data variables:
    exposure_trend_ar6           (run, GMT, region, year) float64 nan ... nan
    mean_exposure_trend_ar6      (GMT, region, year) float64 nan nan ... nan nan
    exposure_trend_country       (run, GMT, country, year) float64 nan ... nan
    mean_exposure_trend_country  (GMT, country, year) float64 nan nan ... nan
    exposure_trend_basin         (run, GMT, basin, year) float64 nan nan ... nan
    mean_exposure_trend_basin    (GMT, basin, year) float64 nan nan ... nan nan

In [22]:
value = ds_le_trends_regions['exposure_trend_ar6'].sel(
    run=2,
    GMT=5,
    region=10,
    year=2020
)

print(value)

<xarray.DataArray 'exposure_trend_ar6' ()>
array(nan)
Coordinates:
    region   int64 10
    run      int64 2
    GMT      int64 5
    year     int64 2020


In [35]:
print(ds_le_trends_regions['exposure_trend_ar6'].sel(
    run=11,
    GMT=20,
    region=25,
))

<xarray.DataArray 'exposure_trend_ar6' (year: 61)>
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])
Coordinates:
    region   int64 25
    run      int64 11
    GMT      int64 20
  * year     (year) int64 1960 1961 1962 1963 1964 ... 2016 2017 2018 2019 2020


In [23]:
# Vérifier si la variable 'exposure_trend_ar6' existe dans le dataset
if 'exposure_trend_ar6' in ds_le_trends_regions:

    # Créer un masque booléen où True indique que la valeur n'est pas NaN
    mask_non_nan = ds_le_trends_regions['exposure_trend_ar6'].notnull()

    # Vérifier s'il existe des valeurs non-NaN dans toutes les dimensions et coordonnées
    all_non_nan = mask_non_nan.all()

    # Afficher le résultat
    if all_non_nan:
        print("Toutes les coordonnées ont des valeurs non nulles et différentes de NaN.")
    else:
        print("Certaines coordonnées contiennent des valeurs NaN ou nulles.")
else:
    print("La variable 'exposure_trend_ar6' n'existe pas dans le dataset.")


Certaines coordonnées contiennent des valeurs NaN ou nulles.


da_regions

In [24]:
d_countries = pk.load(open(data_dir+'{}/country/country_info.pkl'.format('pickles_v3'), 'rb'))
df_countries = d_countries['info_pop']

In [25]:
da_regions = df_countries['region'].unique()

In [26]:
da_regions

array(['South Asia', 'Sub-Saharan Africa', 'Europe & Central Asia',
       'Middle East & North Africa', 'Latin America & Caribbean',
       'East Asia & Pacific', 'North America'], dtype=object)